### ISSUE TITLE
Unable to decode encoded file

### ISSUE THREAD

**Issue by emansih** [quiet/quiet#18]
Hi,

I have a similar issue to #6 . 

$ echo "hello world" >> hello.txt
$ quiet_encode_file audible hello.txt 

I can verify that the program did produce a valid .wav file(there's audio when playing through vlc)
$ file encoded.wav
encoded.wav: RIFF (little-endian) data, WAVE audio, mono 44100 Hz

$ quiet_decode_file audible encoded.wav
failed to open wav file for reading

[encoded.zip](https://github.com/quiet/quiet/files/936752/encoded.zip)
The attached is the zipped file for encoded.wav

**Comment by brian-armstrong** [comment]
Hi @emansih

It looks like you may be supplying encoded.wav to the decoder. This argument should be the destination of where you want the decoded file to go. You can also just leave blank to write to stdout. Likely what's happening is that the program is attempting to open encoded.wav for writing and then can't read it.

Sorry that this program is tricky to use :(

**Comment by emansih** [comment]
thanks! another question, can i have the output as a mp3 file instead of wav file?

**Comment by brian-armstrong** [comment]
@emansih

Quiet itself is unlikely to get this functionality since it uses libsndfile which doesn't support mp3s due to royalty/patent reasons. 

If you want to transcode to mp3 after the fact, it should be relatively easy to do with LAME. Just be aware that mp3, like all lossy codecs, will distort the sound and remove high frequencies. I've only tested quiet a little under compression, and it does work, but you'll need to do some experimentation on the profile to make it reliable :)

**Comment by emansih** [comment]
hmm..ok, so i can use ffmpeg to transcode it without losing any data. mp3 is almost royalty free isn't it? how about other format such as flac, aac, opus?

**Comment by brian-armstrong** [comment]
@emansih

That's a good idea. The encode/decode-file programs aren't very polished, but I think that would be a good improvement. Probably what I would do is let you specify the wave file name and then encode based on the file extension.

My thinking with wav is that people will probably just want to build the wav and then embed it into a larger sound file using a sound editing tool. Wav seems probably best suited for that task
