### ISSUE TITLE
Coding/bitrate improvements

### ISSUE THREAD

**Issue by goblin** [quiet/quiet#40]
AFAIK the best-quality profile bundled is cable-64k, which, if I'm not mistaken, codes 64kbit/s. I think there's much room for improvement. I believe 50dB or better signal-to-noise ratio on most cards is totally achievable when using a cable, and we have about 20kHz of bandwidth available. [Shannon–Hartley theorem](https://en.wikipedia.org/wiki/Shannon%E2%80%93Hartley_theorem) tells us that the theoretical maximum data rate on such a channel is 20000 * log_2(1 + 100000) = 332193 bit/s. Even if we add some margin and make it 17kHz with 30dB SNR, we get theoretical max of 169kbit/s.

The existence of 33.6k modems and the Trellis-coded modulation revolution of ~1982 makes me believe that something nearer this theoretical max should be very much achievable with better coding :-)

I'd be happy to experiment with custom profiles myself, but I don't yet know how they work (and even the bundled ones [produce errors for me](https://github.com/quiet/quiet/issues/39) curently). Not sure if there's an option for Trellis-coded modulation/Viterbi decoding?

**Comment by brian-armstrong** [comment]
There's not really much point to supporting fast transfer via cable. Nobody's phones has headphone jacks anymore anyway. Viterbi is provided by libcorrect or libfec, and accessed via the "v" fecs (v27, v29 etc). If you're not using a cable then you have much larger issues like acoustic echoes.

I'm closing this since it's not really actionable. If you want some guidance on where to look for things in the codebase, feel free to email me, it's easier than trying to communicate via GH issues.
