### ISSUE TITLE
decode_file could not decode recorded output of encode_file

### ISSUE THREAD

**Issue by ashishtilokani** [quiet/quiet#6]
Hi,
I was playing around with decode_file.c and encode_file.c and observed that if encoded.wav (output of encode_file) is recorded using a good quality mic and is used as the input to decode_file.c then its output file is always blank.

Could you please tell me what could be the possible reasons?
I am using AudioRecorder chrome extension.
(https://chrome.google.com/webstore/detail/audiorecorder/enhfkjkjfhhdibpgjmiamdcdgmcjpplk)

Thanks a lot. :) I really appreciate the effort you have put in this project.

**Comment by brian-armstrong** [comment]
Hm, there could be a few factors causing that. Have you tried the encode_soundcard/decode_soundcard binaries, rather than using the .wav file? I think that'd be the first thing I would try. Those binaries can connect directly to your speaker/mic and get good quality sound.

Chrome's webrtc implementation has some features turn on by default, like noise cancellation and echo cancellation, which could affect the recording. I'm not sure if AudioRecorder uses that API. Normally these cancellations are helpful, if you intend to record voice, but they detect modem sounds as being noise and can really distort the modem audio. I don't know if that's for sure causing the behavior you're seeing but that'd be my first guess.

If you take encoded.wav and pass it directly to decode_file, does that work? I know that's sort of cheating but that'd also be useful info for debugging purposes.

**Comment by ashishtilokani** [comment]
Thanks for the reply.

Passing encoded.wav file (original file) directly to decode_file works perfectly. 

Using sound analyzer pro app to record also did not help.
https://play.google.com/store/apps/details?id=com.zephyr.soundAnalyserPRO&hl=en

I tried encode_soundcard/decode_soundcard binaries but port audio functions could not detect any device

PaDeviceInfo *deviceInfo = Pa_GetDeviceInfo(device);
assert(deviceInfo); 

This assertion fails in encode_soundcard.

**Comment by brian-armstrong** [comment]
What platform are you using? I've only been able to test the binaries on OSX so far.

I'm surprised it doesn't work with that app. I do know that some Android devices have multiple mics and will do some kind of echo cancellation with them, but I don't know enough to guess if that's happening here.

I'm stumped as to why it isn't working in your case. It looks like I need better debugging utilities for cases like this. I'll see if I can come up with any easy tests that would work here.

Which modem profile have you been using?

**Comment by ashishtilokani** [comment]
Enabling debugging flags in the liquid library helped. It was failing checksum so I set it to none in the quiet-profile.json. I tried alternative parameters and I was able to see some output. 

I am using ubuntu by the way.

**Comment by brian-armstrong** [comment]
Ah, good sleuthing. I forgot about all the various prints in liquid.

If the checksum is failing then you are likely seeing some sound distortion. I need to work on better instrumenting what the receiver sees.

I just recently did push some receiver debugging which might help you. You can now call `quiet_decoder_enable_stats(decoder)` and then, after calling `quiet_decoder_consume`, do `size_t num_frames; quiet_decoder_frame_stats *stats = quiet_decoder_consume_stats(decoder, &num_frames); stats[0] ...`. The stats object contains some coarse grained info about received frames like signal strength and a pointer to an array of complex symbols after demodulation. That might help tune your setup.

Also, if you're trying the ultrasonic modem profile, I'd recommend bringing the center frequency down to see if that helps. The ultrasonic profiles are generally the hardest to get working, as a lot of systems don't pass higher frequencies.
